# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Windows.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 149)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PortSet = QtWidgets.QGroupBox(self.centralwidget)
        self.PortSet.setObjectName("PortSet")
        self.gridLayout = QtWidgets.QGridLayout(self.PortSet)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ScanPortButton = QtWidgets.QPushButton(self.PortSet)
        self.ScanPortButton.setObjectName("ScanPortButton")
        self.verticalLayout.addWidget(self.ScanPortButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.COMLabel = QtWidgets.QLabel(self.PortSet)
        self.COMLabel.setObjectName("COMLabel")
        self.horizontalLayout.addWidget(self.COMLabel)
        self.COMCB = QtWidgets.QComboBox(self.PortSet)
        self.COMCB.setObjectName("COMCB")
        self.horizontalLayout.addWidget(self.COMCB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OpenFileButton = QtWidgets.QPushButton(self.PortSet)
        self.OpenFileButton.setObjectName("OpenFileButton")
        self.horizontalLayout_2.addWidget(self.OpenFileButton)
        self.FileLineEdit = QtWidgets.QLineEdit(self.PortSet)
        self.FileLineEdit.setReadOnly(True)
        self.FileLineEdit.setClearButtonEnabled(False)
        self.FileLineEdit.setObjectName("FileLineEdit")
        self.horizontalLayout_2.addWidget(self.FileLineEdit)
        self.SendButton = QtWidgets.QPushButton(self.PortSet)
        self.SendButton.setObjectName("SendButton")
        self.horizontalLayout_2.addWidget(self.SendButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.PortSet, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionSaveLog = QtWidgets.QAction(MainWindow)
        self.actionSaveLog.setObjectName("actionSaveLog")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MAX32664-Tool v1.0"))
        self.PortSet.setTitle(_translate("MainWindow", "串口设置"))
        self.ScanPortButton.setText(_translate("MainWindow", "扫描串口"))
        self.COMLabel.setText(_translate("MainWindow", "串口号"))
        self.OpenFileButton.setText(_translate("MainWindow", "打开文件"))
        self.SendButton.setText(_translate("MainWindow", "下载文件"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.menuHelp.setTitle(_translate("MainWindow", "帮助"))
        self.actionOpen_File.setText(_translate("MainWindow", "打开文件"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveLog.setText(_translate("MainWindow", "保存Log"))
        self.actionSaveLog.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "退出"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "关于软件"))
